//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thermota {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thermota.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        internal static string Command_Average {
            get {
                return ResourceManager.GetString("Command_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        internal static string Command_Current {
            get {
                return ResourceManager.GetString("Command_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string Command_Exit {
            get {
                return ResourceManager.GetString("Command_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string Command_Help {
            get {
                return ResourceManager.GetString("Command_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get average temperature.
        /// </summary>
        internal static string Message_Average {
            get {
                return ResourceManager.GetString("Message_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current temperature.
        /// </summary>
        internal static string Message_Current {
            get {
                return ResourceManager.GetString("Message_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the console.
        /// </summary>
        internal static string Message_Exit {
            get {
                return ResourceManager.GetString("Message_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this usage message.
        /// </summary>
        internal static string Message_Help {
            get {
                return ResourceManager.GetString("Message_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the thermometer console!.
        /// </summary>
        internal static string Message_Welcome {
            get {
                return ResourceManager.GetString("Message_Welcome", resourceCulture);
            }
        }
    }
}
